const DIFFICULTY = 3;
const MINE_RATE = 2 * 1000; // 2s
const INITIAL_BALANCE = 1000; // MIL PILA
const MINING_REWARD = 50;

module.exports = { DIFFICULTY, MINE_RATE, INITIAL_BALANCE, MINING_REWARD };
